spring:
  application:
    name: byfood

  datasource:
    url: jdbc:postgresql://localhost:5432/byfood
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080
